### ISSUE TITLE
remote-url is converted to an array option not string

### ISSUE THREAD

**Issue by ali-bugdayci** [langri-sha/npm_lazy#15]
In the following usage:

```
sudo docker run -p 8000:8080 -v /root/.npm_lazy:/root/.npm_lazy  langrisha/npm-lazy remote-url http://registry.npmjs.org --show-config
{ loggingOpts: 
   { logToConsole: true,
     logToFile: false,
     filename: '/root/npm_lazy.log' },
  cacheDirectory: '/root/.npm_lazy',
  cacheAge: 0,
  httpTimeout: 10000,
  maxRetries: 5,
  rejectUnauthorized: true,
  externalUrl: 'http://localhost:8080',
  remoteUrl: [ 'http://registry.npmjs.org' ],
  port: 8080,
  host: '0.0.0.0',
  proxy: { https: undefined, http: undefined } }

url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not object
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at Function.Package.configure (/app/node_modules/npm_lazy/lib/package.js:25:26)
    at start (/app/node_modules/npm_lazy/server.js:64:11)
    at Object.<anonymous> (/app/index.js:29:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by langri-sha** [comment]
Try using `--remote-url` and the options should be parsed fine:

```
sudo docker run \
  -p 8000:8080 -v /root/.npm_lazy:/root/.npm_lazy  \
  langrisha/npm-lazy \
      --remote-url http://registry.npmjs.org  \
      --show-config
```
