### ISSUE TITLE
Running langrisha/npm-lazy:1.11.0 fails with "Error: Cannot find module 'util-deprecate'"

### ISSUE THREAD

**Issue by jamshid** [langri-sha/npm_lazy#25]
I'm getting this in my Docker for Mac 17.06.0-ce environment I just reset. I was able to run the same npmlazy image fine before reset, and it works fine on my other docker servers. Any ideas? 
```
$ docker run -ti langrisha/npm-lazy:1.11.0
module.js:327
    throw err;
    ^

Error: Cannot find module 'util-deprecate'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/node_modules/underscore.string/sprintf.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Found a few hits related to node/npm weirdness but `npm cache clean && npm cache clear && npm outdated --depth=0` and `npm install` doesn't help.

**Comment by jamshid** [comment]
That's unsettling, re-downloading the image fixed this problem.
I just stopped all containers and ran `docker rmi langrisha/npm-lazy:1.11.0` and `docker system prune -f`.
